## @section rabbitmq Configuration
##
rabbitmq:
   ## @param rabbitmq.app App name for rabbitmq
   ##
   app: rabbitmq
   ## @param rabbitmq.name Name for rabbitmq
   ##
   name: rabbitmq
   ## @param rabbitmq.image Image rabbitmq deployment
   ##
   image: rabbitmq
   ## @param rabbitmq.tag Tag for rabbitmq
   ##
   tag: 3-management-alpine
   ## @param rabbitmq.imagePullPolicy Policy for rabbitmq
   ##
   # imagePullPolicy: "IfNotPresent"
   ## @param rabbitmq.replicaCount ReplicaCount for rabbitmq
   ##
   replicaCount: 1
   

## @section PostgreSQL Configuration
##
# postgres:
#    ## @param postgres.app PostgreSQL App
#    ##
#    app: postgres
#    ## @param postgres.name PostgreSQL Name
#    ##
#    name: postgres
#    ## @param postgres.image PostgreSQL Image
#    ##
#    image: peter91peter91/bitnami_postgresql # peter91peter91/iriswebapp_db #localhost:5000/iriswebapp_db  ## postgres:12.6
#    ## @param postgres.tag PostgreSQL Tag
#    tag: v16
#    ## @param postgres.imagePullPolicy PostgreSQL PullPolicy
#    ##
#    #imagePullPolicy: "IfNotPresent"
#    imagePullPolicy: Always   #!!! поставил для тестов
#    ## @param postgres.replicaCount PostgreSQL ReplicaCount
#    ##
#    replicaCount: 1
   
#    ## @param postgres.service PostgreSQL Service
#    ##
#    service:
#     port: 5432

#    ## @param  PostgreSQL Environments
#    ##
#    POSTGRES_USER: postgres
#    POSTGRES_PASSWORD: postgres
#    POSTGRES_ADMIN_USER: raptor
#    POSTGRES_ADMIN_PASSWORD: postgres
#    POSTGRES_DB: iris_db   
#    POSTGRES_PORT: 5432


## @section Iris Frontend Configuration
##
irisapp:
   ## @param irisapp.app Iris Frontend App
   ##
   app: iriswebapp-app
   ## @param irisapp.name Iris Frontend Name
   ##
   name: iriswebapp-app
   ## @param irisapp.image Iris Frontend Image
   ##
   image: peter91peter91/iriswebapp_app #localhost:5000/iriswebapp_app
   ## @param irisapp.tag Iris Frontend Tag
   ##
   tag: v2.4.7
   ## @param irisapp.imagePullPolicy Iris Frontend imagePullPolicy
   ##
   imagePullPolicy: "IfNotPresent"
   #imagePullPolicy: Always   #moiseev- поставил для тестов 
   ## @param irisapp.replicaCount Iris Frontend replicaCount
   ##
   replicaCount: 1

   ## @param irisapp.service Iris Frontend Service
   ##
   service:
     port: 8000   # порт слушает ирис
     nodePort: 31111  #moiseev   # доступ извне- Зафиксировал порт для NodePort

    
   ## @param irisapp.type Iris Frontend Service type
   ##
   type: NodePort

   ## @param  Iris Frontend Environments
   ##
   # psql -U postgres -P 7yLLlgAaRR

   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_ADMIN_USER: postgres
   POSTGRES_ADMIN_PASSWORD: postgres

   POSTGRES_DB: iris_db 
   POSTGRES_PORT: 5432
   #POSTGRES_SERVER: postgres.<name_space>.svc.cluster.local
   #POSTGRES_SERVER: postgres.moiseev-namespace-bitnami-postgres.svc.cluster.local
   POSTGRES_SERVER: moiseev-release-iris-postgresql
   DOCKERIZED: 1
   IRIS_SECRET_KEY: AVerySuperSecretKey-SoNotThisOne
   IRIS_SECURITY_PASSWORD_SALT: ARandomSalt-NotThisOneEither
   IRIS_ADM_USERNAME: administrator
   # Must be 12 characters minimum and contains a capital letter and a number. 
   IRIS_ADM_PASSWORD: Hello12345!
   IRIS_AUTHENTICATION_TYPE: local  #moiseev Добавил. для корректной авторизации
   #IRIS_AUTHENTICATION_CREATE_USER_IF_NOT_EXIST: True #moiseev Добавил для теста
   DB_RETRY_COUNT: 5
   DB_RETRY_DELAY: 5
   INTERFACE_HTTPS_PORT: 443
   IRIS_UPSTREAM_SERVER: 

## @section Iris Backend Configuration 
##
irisworker:
   ## @param irisworker.app Iris Backend App
   ##    
   app: iriswebapp-worker
   ## @param irisworker.name Iris Backend Name
   ##
   name: iriswebapp-worker
   ## @param irisworker.image Iris Backend Image
   ##
   image: peter91peter91/iriswebapp_app #localhost:5000/iriswebapp_app
   ## @param irisworker.tag Iris Backend Tag
   ##
   tag: v2.4.7
   ## @param irisworker.imagePullPolicy Iris Backend imagePullPolicy
   ##
   #imagePullPolicy: Always   #!!! поставил для тестов
   imagePullPolicy: "IfNotPresent"
   ## @param irisworker.replicaCount Iris Backend replicaCount
   ##
   replicaCount: 1

   ## @param  Iris Backend Environments
   ##
    # psql -U postgres -P 7yLLlgAaRR

   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_ADMIN_USER: postgres
   POSTGRES_ADMIN_PASSWORD: postgres

   POSTGRES_DB: iris_db   
   POSTGRES_PORT: 5432
   #POSTGRES_SERVER: postgres.<name_space>.svc.cluster.local
   #POSTGRES_SERVER: postgres.moiseev-namespace-iris.svc.cluster.local
   POSTGRES_SERVER: moiseev-release-iris-postgresql
   DOCKERIZED: 1
   IRIS_SECRET_KEY: AVerySuperSecretKey-SoNotThisOne
   IRIS_SECURITY_PASSWORD_SALT: ARandomSalt-NotThisOneEither
   CELERY_BROKER: "amqp://rabbitmq"  #moiseev тестово добавил для очереди задач rabbit по протоколу amqp 

## @section Nginx Ingress Configuration
##
ingress:
  enabled: true
  name: iris-ingress
  className: nginx
  annotations:
    # Add any annotations specific to your Ingress controller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # Nginx будет переписывать путь запроса  для  маршрутизации запросов к IRIS приложению.
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 
    #nginx.ingress.kubernetes.io/ssl-redirect: "false" #ВЫКЛЮЧАЕМ ПЕРЕНАПРАВЛЕНИЕ НА HTTPS
#########################
#moiseev тестовые конфиги session-cookie для работы с ними кубером-НЕ ПОМОГЛО
    nginx.ingress.kubernetes.io/session-cookie-name: "session" #moiseev 
    nginx.ingress.kubernetes.io/session-cookie-httponly: "true" #moiseev 
    nginx.ingress.kubernetes.io/session-cookie-secure: "true" #moiseev 
    nginx.ingress.kubernetes.io/session-cookie-samesite: "Lax" #moiseev 
    nginx.ingress.kubernetes.io/session-cookie-expires: "86400" #moiseev  
#########################
  hosts:
    - host: iris.local # Nginx Ingress Controller принимает запросы на этот домен
      paths:
        - path: /(.*) # для домена iris.local все запросы, соответствующие пути /(.*), будут направляться на сервис с именем iriswebapp-app на порту 8000.
          pathType: ImplementationSpecific
          serviceName: iriswebapp-app
          servicePort: 8000 

  tls:   #moiseev пробовал комментировать блок 
    - secretName: iris-ingress-tls-secret
      hosts:
        - iris.local
  
